version: "2"

services:
  mlx:
    build: .
    volumes:
      - .:/opt/ib/
    expose:
      - "22"
    environment:
      - VIRTUAL_PORT=22
      - DISPLAY=$DISPLAY
      - XSOCKET=$XSOCKET
      - XAUTHORITY=$XAUTHORITY
